[package]
name = "koi"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["crates/*"]

[features]
default = ["graphics"]
graphics = ["kgraphics"]

[dependencies]
kapp = {path = "crates/kapp", version = "0.1.0", default-features=false}
kudo = {path = "crates/kudo", version = "0.1.0"}
kgraphics = {path = "crates/kgraphics", version = "0.1.0", optional = true}
ktasks = {path = "crates/ktasks", version = "0.1.0"}
kmath = {path = "crates/kmath", version = "0.1.0"}
klog = {path = "crates/klog", version = "0.1.0"}
oorandom = "11.1.3"
kolor = {path = "../../scratchspace/kolor/build/kolor/"}

[target.'cfg(target_arch="wasm32")'.dependencies]
kwasm = {path = "crates/kwasm",  version = "0.1.0"}