[package]
name = "koi"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["crates/*", "third_party/koi_kolor/build/kolor"]


[features]
default = ["graphics", "renderer", "drawer2d", "png", "jpeg"]
graphics = ["kgraphics"]
renderer = []
drawer2d = []
jpeg = ["jpeg-decoder"]

[dependencies]
kapp = {path = "crates/kapp", version = "0.1.0", default-features=false}
kudo = {path = "crates/kudo", version = "0.1.0"}
kgraphics = {path = "crates/kgraphics", version = "0.1.0", optional = true}
ktasks = {path = "crates/ktasks", version = "0.1.0"}
kmath = {path = "crates/kmath", version = "0.1.0"}
klog = {path = "crates/klog", version = "0.1.0"}
oorandom = "11.1.3"
png = {git = "https://github.com/image-rs/image-png", optional = true}
jpeg-decoder = {version = "0.1.20", default-features = false, optional = true}

# This is copied / modified locally because it can't build presently with `glam` disabled.
kolor = {path = "third_party/koi_kolor/build/kolor", default-features=false, features=["f32", "std"]}

[target.'cfg(target_arch="wasm32")'.dependencies]
kwasm = {path = "crates/kwasm",  version = "0.1.0"}