[package]
name = "kreflect_derive"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"


[dependencies]
kreflect_common = {path = "../kreflect_common", features=["proc_macro"]}

[lib]
proc-macro = true