[package]
name = "kudo_derive"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2018"

[dependencies]
kudo_derive_impl = {path = "kudo_derive_impl"}
kreflect_common = {path = "../../kreflect/kreflect_common", features = ["proc_macro"]}

[lib]
proc-macro = true