[package]
name = "kreflect"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2021"

[dependencies]
kreflect_common = {path = "kreflect_common"}
kreflect_derive = {path = "kreflect_derive"}

[lib]
