[package]
name = "kapp_platform_common"
version = "0.1.0"
authors = ["Ian Kettlewell <ian.kettlewell@gmail.com>"]
edition = "2021"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
raw-window-handle = "0.4.2"
kserde = {path = "../../kserde", optional = true}
